sonar.organization=fulcrumapp
sonar.projectKey=fulcrumapp_query-sql
sonar.projectName=query-sql

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.*
sonar.exclusions=dist/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
