name: 🧪 CI
on: [pull_request]

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: ⎔ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@fulcrumapp"

      - name: 📥 Install Dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔬 Lint
        run: yarn run lint || true

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: ⎔ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@fulcrumapp"

      - name: 📥 Install Dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔎 Type Check
        run: yarn run typecheck

  jest:
    name: 🃏 Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: ⎔ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@fulcrumapp"

      - name: 📥 Install Dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🃏 Run Jest
        run: yarn run test
